### ISSUE TITLE
Incompatible with "Hungry Cows"

### ISSUE THREAD

**Issue by Mirsario** [Crendgrim/DynamicCrosshair#102]
Using the following mod: 
https://modrinth.com/mod/hungrycows
and hovering over cows with shears causes the following crash:

```
java.lang.AbstractMethodError: Method net/minecraft/class_1430.method_27072()Z is abstract
	at net.minecraft.class_1430.method_27072(class_1430.java)
	at mod.crend.dynamiccrosshair.handler.VanillaEntityHandler.checkEntity(VanillaEntityHandler.java:61)
	at mod.crend.dynamiccrosshair.handler.VanillaApiImpl.computeFromEntity(VanillaApiImpl.java:101)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvancedByHand(CrosshairHandler.java:90)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvanced(CrosshairHandler.java:118)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:208)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:316)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:364)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:385)
	at net.minecraft.class_329.handler$bac000$dynamiccrosshair$tickDynamicCrosshair(class_329.java:2404)
	at net.minecraft.class_329.method_1748(class_329.java:1195)
	at net.minecraft.class_329.method_39191(class_329.java:1159)
	at net.minecraft.class_310.method_1574(class_310.java:1846)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

Occurred in MC 1.20.1, DC 7.4.4, and HC 1.4.0 (all is latest at the time).

**Comment by Mirsario** [comment]
Notifying HC's author: @pnk2u

**Comment by pnk2u** [comment]
Hi, thanks for bringing this to my attention, I assumed responsibility for this, version 1.4.1 provides a fix that hopefully works for you.

**Comment by Mirsario** [comment]
Thanks!
