### ISSUE TITLE
Called getBlockState() without a targeted block

### ISSUE THREAD

**Issue by maxvar** [Crendgrim/DynamicCrosshair#37]
The log is filled with those errors right from the game start and world load (repeated 19 times). No such errors later in the game.
Mod versions are dynamiccrosshair-5.0+1.19.3-fabric.jar and dynamiccrosshair-compat-2.0+1.19.3.jar
```
[12:23:31] [Render thread/ERROR]: Encountered invalid context state: 
mod.crend.dynamiccrosshair.api.InvalidContextState: Called getBlockState() without a targeted block!
	at mod.crend.dynamiccrosshair.api.CrosshairContext.getBlockState(CrosshairContext.java:117) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.api.CrosshairContext.getBlock(CrosshairContext.java:126) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.compat.techreborn.ApiImplTechReborn.computeFromItem(ApiImplTechReborn.java:87) ~[dynamiccrosshair-compat-2.0+1.19.3.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvancedFromItem(CrosshairHandler.java:60) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvancedByHand(CrosshairHandler.java:88) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvanced(CrosshairHandler.java:93) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:168) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:222) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:262) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:283) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at net.minecraft.class_329.handler$bab000$dynamiccrosshair$tickDynamicCrosshair(class_329.java:6048) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1748(class_329.java:1311) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_39191(class_329.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1826) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1150) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[minecraft-1.19.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]

………

[12:23:52] [Render thread/ERROR]: Encountered invalid context state: 
mod.crend.dynamiccrosshair.api.InvalidContextState: Called getBlockState() without a targeted block!
	at mod.crend.dynamiccrosshair.api.CrosshairContext.getBlockState(CrosshairContext.java:117) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.api.CrosshairContext.getBlock(CrosshairContext.java:126) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.compat.techreborn.ApiImplTechReborn.computeFromItem(ApiImplTechReborn.java:87) ~[dynamiccrosshair-compat-2.0+1.19.3.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvancedFromItem(CrosshairHandler.java:60) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvancedByHand(CrosshairHandler.java:88) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvanced(CrosshairHandler.java:93) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:168) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:222) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:262) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:283) ~[dynamiccrosshair-5.0+1.19.3-fabric.jar:?]
	at net.minecraft.class_329.handler$bab000$dynamiccrosshair$tickDynamicCrosshair(class_329.java:6048) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1748(class_329.java:1311) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_39191(class_329.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1826) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1150) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[minecraft-1.19.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]

```

**Comment by Crendgrim** [comment]
Thank you for the report! Should be fixed in Dynamic Crosshair Compat 3.1.
