### ISSUE TITLE
[Bug] Exception error when looking at a block from BYG

### ISSUE THREAD

**Issue by pokesmells** [Crendgrim/DynamicCrosshair#44]
I get this error when moving around the end or rather when my crosshair looks upon the block mentioned in the error.

**Exception occurred during evaluation of API byg
java.lang.NoClassDefFoundError: potionstudios/byg/common/block/end/TheriumCrystalBlock
	at mod.crend.dynamiccrosshair.compat.byg.ApiImplOhTheBiomesYoullGo.computeFromBlock(ApiImplOhTheBiomesYoullGo.java:71)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvancedByHand(CrosshairHandler.java:99)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvanced(CrosshairHandler.java:112)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:199)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:304)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:344)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:365)
	at net.minecraft.class_329.handler$fed000$dynamiccrosshair$tickDynamicCrosshair(class_329.java:26042)
	at net.minecraft.class_329.method_1748(class_329.java:1305)
	at net.minecraft.class_329.method_39191(class_329.java:1271)
	at net.minecraft.class_310.method_1574(class_310.java:1792)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: potionstudios.byg.common.block.end.TheriumCrystalBlock
	... 18 more**
	
	
	I get some lag if I stare at it too long.
	
	
	Fabric 0.14.19
	MC Version 1.19.2
	dynamiccrosshair-5.4+1.19.2-fabric
	dynamiccrosshair-compat-3.3.1+1.19.2

**Comment by Crendgrim** [comment]
This exception gets thrown because Therium got reworked in the beta version of BYG (commit dates to December 2022). However, there still hasn't been a new stable release of BYG since. I don't really want to keep the compat layer up to date with beta versions of other mods.

Am I right in assuming that this is merely an error in the game log and does not inhibit gameplay in any way?

**Comment by Crendgrim** [comment]
Forgot to close this issue because it was in the other repository; was fixed with DynamicCrosshairCompat 3.3.3
