### ISSUE TITLE
Mod dynamiccrosshair provides a broken implementation of ModMenuApi

### ISSUE THREAD

**Issue by TitanGames-729** [Crendgrim/DynamicCrosshair#80]
Hi! tried to run this mod on fabric 1.20.4 but it gives me the following

`java.lang.NoClassDefFoundError: Could not initialize class mod.crend.dynamiccrosshair.config.ConfigHandler
	at mod.crend.dynamiccrosshair.fabric.screen.ModMenuIntegration.getModConfigScreenFactory(ModMenuIntegration.java:12) ~[dynamiccrosshair-7.7+1.20.4-fabric.jar:?]
	at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$1(ModMenu.java:76) ~[modmenu-9.0.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.terraformersmc.modmenu.ModMenu.onInitializeClient(ModMenu.java:71) ~[modmenu-9.0.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) ~[fabric-loader-0.15.7.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:487) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[Fabric%201.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalAccessError: class dev.isxander.yacl3.config.v2.impl.serializer.GsonConfigSerializer$Builder tried to access private method 'void net.minecraft.class_2561$class_2562.<init>()' (dev.isxander.yacl3.config.v2.impl.serializer.GsonConfigSerializer$Builder and net.minecraft.class_2561$class_2562 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1e67a849) [in thread "Render thread"]
	at dev.isxander.yacl3.config.v2.impl.serializer.GsonConfigSerializer$Builder.lambda$new$0(GsonConfigSerializer.java:207) ~[yet-another-config-lib-fabric-3.2.2+1.20.jar:?]
	at dev.isxander.yacl3.config.v2.impl.serializer.GsonConfigSerializer$Builder.lambda$appendGsonBuilder$2(GsonConfigSerializer.java:238) ~[yet-another-config-lib-fabric-3.2.2+1.20.jar:?]
	at dev.isxander.yacl3.config.v2.impl.serializer.GsonConfigSerializer$Builder.build(GsonConfigSerializer.java:250) ~[yet-another-config-lib-fabric-3.2.2+1.20.jar:?]
	at dev.isxander.yacl3.config.v2.impl.serializer.GsonConfigSerializer$Builder.build(GsonConfigSerializer.java:200) ~[yet-another-config-lib-fabric-3.2.2+1.20.jar:?]
	at mod.crend.yaclx.opt.WithYacl.lambda$new$2(WithYacl.java:37) ~[yaclx-1.12+1.20.2-45e0ba3e39285b53.jar:?]
	at dev.isxander.yacl3.config.v2.impl.ConfigClassHandlerImpl.<init>(ConfigClassHandlerImpl.java:54) ~[yet-another-config-lib-fabric-3.2.2+1.20.jar:?]
	at dev.isxander.yacl3.config.v2.impl.ConfigClassHandlerImpl$BuilderImpl.build(ConfigClassHandlerImpl.java:241) ~[yet-another-config-lib-fabric-3.2.2+1.20.jar:?]
	at mod.crend.yaclx.opt.WithYacl.<init>(WithYacl.java:38) ~[yaclx-1.12+1.20.2-45e0ba3e39285b53.jar:?]
	at mod.crend.yaclx.opt.ConfigStore.init(ConfigStore.java:147) ~[yaclx-1.12+1.20.2-45e0ba3e39285b53.jar:?]
	at mod.crend.yaclx.opt.ConfigStore.<init>(ConfigStore.java:87) ~[yaclx-1.12+1.20.2-45e0ba3e39285b53.jar:?]
	at mod.crend.dynamiccrosshair.config.ConfigHandler.<clinit>(ConfigHandler.java:11) ~[dynamiccrosshair-7.7+1.20.4-fabric.jar:?]
	at mod.crend.dynamiccrosshair.DynamicCrosshair.init(DynamicCrosshair.java:30) ~[dynamiccrosshair-7.7+1.20.4-fabric.jar:?]
	at mod.crend.dynamiccrosshair.fabric.DynamicCrosshairFabric.onInitializeClient(DynamicCrosshairFabric.java:15) ~[dynamiccrosshair-7.7+1.20.4-fabric.jar:?]
	... 7 more`
	
	after removing modmenu it gives:
	
	`
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'dynamiccrosshair'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalAccessError: class dev.isxander.yacl3.config.v2.impl.serializer.GsonConfigSerializer$Builder tried to access private method 'void net.minecraft.class_2561$class_2562.<init>()' (dev.isxander.yacl3.config.v2.impl.serializer.GsonConfigSerializer$Builder and net.minecraft.class_2561$class_2562 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1e67a849)
	at dev.isxander.yacl3.config.v2.impl.serializer.GsonConfigSerializer$Builder.lambda$new$0(GsonConfigSerializer.java:207)
	at dev.isxander.yacl3.config.v2.impl.serializer.GsonConfigSerializer$Builder.lambda$appendGsonBuilder$2(GsonConfigSerializer.java:238)
	at dev.isxander.yacl3.config.v2.impl.serializer.GsonConfigSerializer$Builder.build(GsonConfigSerializer.java:250)
	at dev.isxander.yacl3.config.v2.impl.serializer.GsonConfigSerializer$Builder.build(GsonConfigSerializer.java:200)
	at mod.crend.yaclx.opt.WithYacl.lambda$new$2(WithYacl.java:37)
	at dev.isxander.yacl3.config.v2.impl.ConfigClassHandlerImpl.<init>(ConfigClassHandlerImpl.java:54)
	at dev.isxander.yacl3.config.v2.impl.ConfigClassHandlerImpl$BuilderImpl.build(ConfigClassHandlerImpl.java:241)
	at mod.crend.yaclx.opt.WithYacl.<init>(WithYacl.java:38)
	at mod.crend.yaclx.opt.ConfigStore.init(ConfigStore.java:147)
	at mod.crend.yaclx.opt.ConfigStore.<init>(ConfigStore.java:87)
	at mod.crend.dynamiccrosshair.config.ConfigHandler.<clinit>(ConfigHandler.java:11)
	at mod.crend.dynamiccrosshair.DynamicCrosshair.init(DynamicCrosshair.java:30)
	at mod.crend.dynamiccrosshair.fabric.DynamicCrosshairFabric.onInitializeClient(DynamicCrosshairFabric.java:15)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more`
	
	mod list:
	
	`[14:37:39] [main/INFO]: Loading 177 mods:
	- advancementinfo 1.20.4-fabric0.91.2-1.4
	- ambientsounds 5.3.5
	- architectury 11.1.17
	- badoptimizations 2.1.0
	- bobby 5.1.0+mc1.20.4
	   |-- com_typesafe_config 1.4.2
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- cameraoverhaul 1.4.0-fabric-universal
	- chat_heads 0.10.32
	- citresewn 1.1.3+1.20
	   \-- citresewn-defaults 1.1.3+1.20
	- cloth-config 13.0.121
	   \-- cloth-basic-math 0.6.1
	- cmdkeybind 1.6.3-1.20.4
	   \-- kyrptconfig 1.6.0-1.20.4
	- collective 7.40
	- continuity 3.0.0-beta.4+1.20.2
	- creativecore 2.11.16
	   \-- net_neoforged_bus 7.2.0
	- cupboard 1.20.1-2.6
	- customsplashscreen 2.1.1
	- distanthorizons 2.0.2-a-dev
	- dynamiccrosshair 7.7+1.20.4
	   \-- yaclx 1.12+1.20.2
	- eatinganimationid 1.20+1.9.5
	- enhancedblockentities 0.9.1+1.20.2
	   |-- advanced_runtime_resource_pack 0.8.0
	   \-- spruceui 5.0.3+1.20.2
	- enhancedvisuals 1.6.9
	- entity_model_features 1.3
	- entity_texture_features 5.2.3
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- equipmentcompare 1.3.8
	   |-- cardinal-components-base 5.2.0
	   \-- cardinal-components-entity 5.2.0
	- exordium 1.2.1
	- extrasounds 2.3.1+1.20.4~lonefelidae16-build.3
	   |-- advanced_runtime_resource_pack 0.8.0
	   \-- soundcategories 1.2.4+1.20.4~lonefelidae16-git+07b73076
	- fabric-api 0.96.11+1.20.4
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.15+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.4+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.4+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.1+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.26+58f8c0124f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.9+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.65+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.14+080016e44f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.20+df798a894f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.11+eb30349a4f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- fabricskyboxes 0.7.3+mc1.20.2
	- forgeconfigapiport 20.4.3
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- fpsreducer 1.20.4-2.7
	- fsb-interop 1.3.6+mc1.20.2-build.52
	- iceberg 1.1.18
	- indium 1.0.30+mc1.20.4
	- interactic 0.2.2+1.20.3
	- inventoryprofilesnext 1.10.9
	- iris 1.7.0-snapshot+mc1.20.4-5983468
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- itemborders 1.2.1
	- itemswapper 0.5.6
	- java 17
	- lambdynlights 2.3.4+1.20.4
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.3+1.20.2
	- legendarytooltips 1.4.5
	- libipn 4.0.1
	- litematica 0.17.2
	- litematica_printer 3.2
	- lithium 0.12.1
	- malilib 0.18.1
	- memoryleakfix 1.1.5
	- minecraft 1.20.4
	- modernfix 5.14.0+mc1.20.4
	- modflared 1.2.0+release.22
	- moreadvancementsmod 1.4.0-1.20.4
	- morechathistory 1.3.0
	- moreculling 1.20.4-0.22.1
	   |-- conditional-mixin 0.3.2
	   \-- mixinsquared 0.1.1
	- no-telemetry 1.8.0
	- nochatreports 1.20.4-v2.5.0
	- owo 0.12.5+1.20.3
	   \-- blue_endless_jankson 1.2.2
	- presencefootsteps 1.11.2
	   \-- kirin 1.17.0+1.20.4
	- prism 1.0.6
	- roughlyenoughitems 14.0.688
	   \-- error_notifier 1.0.9
	- smoothchunk 1.20.1-3.6
	- sodium 0.5.8+mc1.20.4
	- sound_physics_remastered 1.20.4-1.3.1
	- starlight 1.1.3+fabric.f5dcd1a
	- travelerstitles 1.20.4-Fabric-4.4.0
	   \-- org_reflections_reflections 0.10.2
	- visuality 0.7.3+1.20.4
	- visualoverhaul 5.1.0
	   \-- midnightlib 1.5.3
	- vmp 0.2.0+beta.7.138
	   \-- com_ibm_async_asyncutil 0.1.0
	- voicechat 1.20.4-2.5.9
	- xaerominimap 24.0.2
	- xaeroworldmap 1.38.1
	- yet_another_config_lib_v3 3.2.2+1.20
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- yungsapi 1.20.4-Fabric-4.4.2
	   |-- org_javassist_javassist 3.29.2-GA
	   \-- org_reflections_reflections 0.10.2
	- zoomify 2.13.0
	   |-- com_akuleshov7_ktoml-core-jvm 0.5.1
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6`

**Comment by Crendgrim** [comment]
Update YACL (yet-another-config-lib).
