### ISSUE TITLE
[Bug] Crash when switching world by clicking NPCs in Hypixel

### ISSUE THREAD

**Issue by OriginCode** [Crendgrim/DynamicCrosshair#86]
Minecraft Version: 1.21
Fabric Version: 0.15.11
Mod Version: 8.0.1+1.21

Full Log:
https://pastebin.aosc.io/paste/SkjqBRJanJbajihmp7yOoQ/raw

Exception of interest:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_239.method_17783()" because "this.previousHitResult" is null
	at mod.crend.libbamboo.event.ClientEventHandler$GameState.tick(ClientEventHandler.java:64)
	at mod.crend.libbamboo.event.ClientEventHandler.tick(ClientEventHandler.java:219)
	at mod.crend.libbamboo.fabric.LibBambooMod.lambda$onInitializeClient$0(LibBambooMod.java:12)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$bmc000$fabric-lifecycle-events-v1$onEndTick(class_310.java:13183)
	at net.minecraft.class_310.method_1574(class_310.java:2012)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by Crendgrim** [comment]
Thank you for the report! I have pushed version 8.0.2 that should hopefully fix this.
