### ISSUE TITLE
Error on hover over villager

### ISSUE THREAD

**Issue by Mentalgen** [Crendgrim/DynamicCrosshair#90]
It appears that whenever I hover over a villager, Minecraft throws an error:

```[18:18:41] [Render thread/ERROR]:
 Encountered an unexpected error. This usually is due to outdated mod support.
java.lang.IllegalStateException: Cannot load Villager offers on the client
	at net.minecraft.class_3988.method_8264(class_3988.java:109) ~[client-intermediary.jar:?]
	at net.minecraft.class_3988.dynamiccrosshair$compute(class_3988.java:519) ~[client-intermediary.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvancedFromEntity(CrosshairHandler.java:80) ~[dynamiccrosshair-8.0.2+1.21-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvancedByHand(CrosshairHandler.java:97) ~[dynamiccrosshair-8.0.2+1.21-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:106) ~[dynamiccrosshair-8.0.2+1.21-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:207) ~[dynamiccrosshair-8.0.2+1.21-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:255) ~[dynamiccrosshair-8.0.2+1.21-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:280) ~[dynamiccrosshair-8.0.2+1.21-fabric.jar:?]
	at mod.crend.dynamiccrosshair.fabric.DynamicCrosshairFabric.lambda$onInitializeClient$0(DynamicCrosshairFabric.java:20) ~[dynamiccrosshair-8.0.2+1.21-fabric.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.3.1+8f3583aed1-2aae234d8bd144df.jar:?]
	at net.minecraft.class_310.handler$bko000$fabric-lifecycle-events-v1$onEndTick(class_310.java:12683) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2012) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1246) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]```
	
I'm assuming the crosshair should change when hovering over a villager?

**Comment by Crendgrim** [comment]
Thanks for the report, fixed!
